# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
